playtop_exclude: # List of players excluded from appearing in the playtime top list
  - Notch
  - Herobrine
  - Steve
  - Alex

milestones:
  - time: "3h"
    message: "ALL:&6{player} has a reached playtime of 3 hours!"
    permission: "minecraft.dummy.permission"
  - time: "6h"
    messages:
      - "ALL:&6{player} has a reached playtime of 6 hours!"
    permissions:
      - "minecraft.dummy.permission"
    commands:
      - "give {player} minecraft:diamond 1"
  - time: "12h"
    message: "ALL:&6{player} has a reached playtime of 12 hours!"
    permission: "minecraft.dummy.permission"
  - time: "1d"
    message: "ALL:&6{player} has a reached playtime of 1 day!"
    permission: "minecraft.dummy.permission"