milestones:
  - time: "3h"
    message: "ALL:&g{player} has a reached playtime of 3 hours!"
    permission: "minecraft.dummy.permission"
  - time: "6h"
    message: "ALL:&g{player} has a reached playtime of 6 hours!"
    permission: "minecraft.dummy.permission"
  - time: "12h"
    message: "ALL:&g{player} has a reached playtime of 12 hours!"
    permission: "minecraft.dummy.permission"
  - time: "1d"
    message: "ALL:&g{player} has a reached playtime of 1 day!"
    permission: "minecraft.dummy.permission"